language: c
dist: focal
compiler: gcc
before_install:
- sudo apt-get install -y libpam0g-dev expect
script:
- cmake --configure .
- cmake --build .
- ls -l
- bash test.sh

addons:
  apt:
    update: true
  coverity_scan:
    project:
      name: kravietz/poppassd-ceti
      version: 188
      description: Travic-CI scan
    notification_email: pawel.krawczyk@hush.com
    build_command: cmake --build .
    branch_pattern: master

env:
  global:
    secure: DJooeo3P1YjS6aeQqI3Ehsfz8ihqv1zFxDvcW1t3Ctv4H/3ZxxwgmVDWbiDvAg1cF+A8uc5Q5sghuBNNK7r36FfwvLWdcrENseexQfSuO0ruMVXueqdTK3E4xNQWE6tlCj2Yt8zsdAo+epDZf7/uwO/9KsOX+kbH/YPSMTVa5BR0ts3fEm/iWMrPMntXOfPQFASOOFvZeIXy6jE4IP5zja4gbSmCYn8AGtrriczfLElLUDKXBTfmXqrEF4kTowc3Tt5lJnDcVNGHZSYFvuEkVBZ3Q7kbgKRud8I80yLOHj+0JjxsmlGZWPO7ferIsld58D98UkZxuLFLquLhegATU3fCgZtZDpnI2llicZ5CDKuv0hhFFUB37llnr+AEbTixhG5L6fQ1nPKx8yQiPSwJdJKtFiTZPUYHv277v8Ao7xJZGtUx+azsavsFOVcPQO9nUtlV2ClL312+zvf2UxkSdIXCtt+JRUp7FLpKnwpkc4pMuxF+cY52/pNLkczAEWXDzakE39alqTWHYPRQg2BZNtZTCScyAeMRXqcs5TIkrOyIZkZ7SYrXYDLQtOc6GTdQQPsZnhDf4TlLtggPQXYqA0yk2Lfik6HcnAQj1zkGK2qAa+gTlALpDgn6LDjuNOrcdDoaCe1rrw64kk5BgjBIf7hiJ4PDGTtvRQPgoTvvI8s=